=== iceShaver/HiH/HiH_XML/aktorzy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:annotation>
    <xs:documentation xml:lang="pl">
      XML Schema do pliku aktorzy
    </xs:documentation>
  </xs:annotation>
  
  
  <xs:element name="ID_osoby" type="ID_osoby_typ"/>
  <xs:element name="imie" type="xs:string"/>
  <xs:element name="nazwisko" type="xs:string"/>
  <xs:element name="data_urodzenia" type="xs:date"/>
  <xs:element name="plec" type="plec_typ"/>
  <xs:element name="miejsce_urodzenia" type="xs:string" />


  <xs:simpleType name="ID_osoby_typ">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}-\d{4}-[A-Z]{1}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ID_filmu_typ">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}-\d{4}" />
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="plec_typ">
    <xs:restriction base="xs:string">
      <xs:pattern value="kobieta|mezczyzna"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="gatunek_typ">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Horror" />
      <xs:enumeration value="Dokument" />
      <xs:enumeration value="Komedia" />
      <xs:enumeration value="Dramat" />
      <xs:enumeration value="Historyczny" />
      <xs:enumeration value="Wojenny" />
      <xs:enumeration value="Sci-Fi" />
      <xs:enumeration value="Fantasy" />
      <xs:enumeration value="Akcja" />
    </xs:restriction>
  </xs:simpleType>


  <xs:element name="aktorzy" type="aktorzy_typ" />

  <xs:complexType name="aktorzy_typ">
    <xs:sequence>
      <xs:element name="aktor" type="aktor_typ" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="aktor_typ">
    <xs:sequence>
      <xs:element ref="ID_osoby" />
      <xs:element ref="imie"/>
      <xs:element ref="nazwisko"/>
      <xs:element ref="plec"/>
      <xs:element ref="data_urodzenia"/>
      <xs:element ref="miejsce_urodzenia"/>
      <xs:element name="filmy" type="filmy_typ" maxOccurs="unbounded" />
      <xs:element name="rodzina">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="partner">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:maxLength value ="100" />
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="dzieci" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name ="zdjecie" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="filmy_typ">
    <xs:sequence>
      <xs:element name ="film" type="film_typ" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="film_typ" >
    <xs:sequence>
      <xs:element name="ID_filmu" type="ID_filmu_typ" />
      <xs:element name="tytul" type="tytul_typ" maxOccurs="unbounded" />
      <xs:element name="rok_premiery" type="xs:date" />
      <xs:element name="kraj" type="xs:string" maxOccurs="unbounded" />
      <xs:element name="rezyser" type="rezyser_typ" />
      <xs:element name="gatunek" type ="gatunek_typ" maxOccurs="unbounded" />
      <xs:element name="budzet" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="kadr" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="tytul_typ">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="jezyk" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="rezyser_typ">
    <xs:sequence>
      <xs:element ref="ID_osoby" />
      <xs:element ref="imie" />
      <xs:element ref="nazwisko" />
      <xs:element ref="plec" />
      <xs:element ref="data_urodzenia" />
      <xs:element ref="miejsce_urodzenia"/>
      <xs:element name="kolor_oczu" type="kolor_oczu_typ" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="kolor_oczu_typ">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Niebieskie" />
      <xs:enumeration value="Brazowe" />
      <xs:enumeration value="Zielone" />
      <xs:enumeration value="Piwne" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== iceShaver/HiH/HiH_XML/aktorzy.xml
<?xml version="1.0" encoding="utf-8"?>
<aktorzy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="aktorzy.xsd">
  <aktor zdjecie="img/schwarzenegger.jpg">
    <ID_osoby>AS-1947-A</ID_osoby>
    <imie>Arnold</imie>
    <nazwisko>Schwarzenegger</nazwisko>
    <plec>mezczyzna</plec>
    <data_urodzenia>1947-07-30</data_urodzenia>
    <miejsce_urodzenia>Thal, Austria</miejsce_urodzenia>
    <filmy>
      <film kadr="/img/terminator.jpg">
        <ID_filmu>TR-1984</ID_filmu>
        <tytul jezyk="polski">Terminator</tytul>
        <tytul jezyk="angielski">The Terminator</tytul>
        <rok_premiery>1984-10-26</rok_premiery>
        <kraj>USA</kraj>
        <kraj>Wielka Brytania</kraj>
        <rezyser>
          <ID_osoby>JC-1954-K</ID_osoby>
          <imie>James</imie>
          <nazwisko>Cameron</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1954-08-16</data_urodzenia>
          <miejsce_urodzenia>Kapuskasing, Kanada</miejsce_urodzenia>
        <kolor_oczu>Niebieskie</kolor_oczu>
        </rezyser>
        <gatunek>Akcja</gatunek>
        <gatunek>Sci-Fi</gatunek>
        <budzet>78371200</budzet>
      </film>
    </filmy>
  <rodzina>
    <partner>
      Suzy Amis
    </partner>
  <dzieci>Nie wiadomo</dzieci>
  </rodzina>
  </aktor>
  
<aktor zdjecie="img/schwarzenegger.jpg">
    <ID_osoby>AS-1947-A</ID_osoby>
    <imie>Arnold</imie>
    <nazwisko>Schwarzenegger</nazwisko>
    <plec>mezczyzna</plec>
    <data_urodzenia>1947-07-30</data_urodzenia>
    <miejsce_urodzenia>Thal, Austria</miejsce_urodzenia>
    <filmy>
      <film kadr="/img/terminator.jpg">
        <ID_filmu>TR-1984</ID_filmu>
        <tytul jezyk="polski">Terminator</tytul>
        <tytul jezyk="angielski">The Terminator</tytul>
        <rok_premiery>1984-10-26</rok_premiery>
        <kraj>USA</kraj>
        <kraj>Wielka Brytania</kraj>
        <rezyser>
          <ID_osoby>JC-1954-K</ID_osoby>
          <imie>James</imie>
          <nazwisko>Cameron</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1954-08-16</data_urodzenia>
          <miejsce_urodzenia>Kapuskasing, Kanada</miejsce_urodzenia>
        <kolor_oczu>Niebieskie</kolor_oczu>
        </rezyser>
        <gatunek>Akcja</gatunek>
        <gatunek>Sci-Fi</gatunek>
        <budzet>78371200</budzet>
      </film>
    </filmy>
  <rodzina>
    <partner>
      Suzy Amis
    </partner>
  <dzieci>Nie wiadomo</dzieci>
  </rodzina>
  </aktor>
<aktor zdjecie="img/schwarzenegger.jpg">
    <ID_osoby>AS-1947-A</ID_osoby>
    <imie>Arnold</imie>
    <nazwisko>Schwarzenegger</nazwisko>
    <plec>mezczyzna</plec>
    <data_urodzenia>1947-07-30</data_urodzenia>
    <miejsce_urodzenia>Thal, Austria</miejsce_urodzenia>
    <filmy>
      <film kadr="/img/terminator.jpg">
        <ID_filmu>TR-1984</ID_filmu>
        <tytul jezyk="polski">Terminator</tytul>
        <tytul jezyk="angielski">The Terminator</tytul>
        <rok_premiery>1984-10-26</rok_premiery>
        <kraj>USA</kraj>
        <kraj>Wielka Brytania</kraj>
        <rezyser>
          <ID_osoby>JC-1954-K</ID_osoby>
          <imie>James</imie>
          <nazwisko>Cameron</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1954-08-16</data_urodzenia>
          <miejsce_urodzenia>Kapuskasing, Kanada</miejsce_urodzenia>
        <kolor_oczu>Niebieskie</kolor_oczu>
        </rezyser>
        <gatunek>Akcja</gatunek>
        <gatunek>Sci-Fi</gatunek>
        <budzet>78371200</budzet>
      </film>
    </filmy>
  <rodzina>
    <partner>
      Suzy Amis
    </partner>
  <dzieci>Nie wiadomo</dzieci>
  </rodzina>
  </aktor>
</aktorzy>

=== iceShaver/HiH/HIH2/aktorzy.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="html1.xsl"?>
<aktorzy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="aktorzy.xsd">


  <aktor zdjecie="img/schwarzenegger.jpg">
    <ID_osoby>AS-1947-A</ID_osoby>
    <imie>Arnold</imie>
    <nazwisko>Schwarzenegger</nazwisko>
    <plec>mezczyzna</plec>
    <data_urodzenia>1947-07-30</data_urodzenia>
    <miejsce_urodzenia>Thal, Austria</miejsce_urodzenia>
    <link>http://www.schwarzenegger.com/</link>
    <filmy>
      <film kadr="img/terminator.jpeg">
        <ID_filmu>TR-1984</ID_filmu>
        <tytul jezyk="polski">Terminator</tytul>
        <tytul jezyk="angielski">The Terminator</tytul>
        <rok_premiery>1984-10-26</rok_premiery>
        <kraj>USA</kraj>
        <kraj>Wielka Brytania</kraj>
        <rezyser>
          <ID_osoby>JC-1954-K</ID_osoby>
          <imie>James</imie>
          <nazwisko>Cameron</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1954-08-16</data_urodzenia>
          <miejsce_urodzenia>Kapuskasing, Kanada</miejsce_urodzenia>
          <kolor_oczu>Niebieskie</kolor_oczu>
        </rezyser>
        <gatunek>Akcja</gatunek>
        <gatunek>Sci-Fi</gatunek>
        <budzet>78371200</budzet>
      </film>
      <film kadr="img/conan.jpg">
        <ID_filmu>CN-1982</ID_filmu>
        <tytul jezyk="polski">Conan Barbarzyńca</tytul>
        <tytul jezyk="angielski">Conan The Barbarian</tytul>
        <rok_premiery>1982-09-23</rok_premiery>
        <kraj>USA</kraj>
        <rezyser>
          <ID_osoby>JM-1944-S</ID_osoby>
          <imie>John</imie>
          <nazwisko>Milius</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1944-04-11</data_urodzenia>
          <miejsce_urodzenia>Saint Luois, Missouri</miejsce_urodzenia>
          <kolor_oczu>N/A</kolor_oczu>
        </rezyser>
        <gatunek>Przygodowy</gatunek>
        <budzet>16000000</budzet>
      </film>
    </filmy>
    <rodzina>
      <partner>
        Suzy Amis
      </partner>
      <dzieci>Nie wiadomo</dzieci>
    </rodzina>
  </aktor>

  <aktor zdjecie="img/stallone.jpg">
    <ID_osoby>SS-1947-N</ID_osoby>
    <imie>Sylvester</imie>
    <nazwisko>Stallone</nazwisko>
    <plec>mezczyzna</plec>
    <data_urodzenia>1946-06-06</data_urodzenia>
    <miejsce_urodzenia>Nowy Jork</miejsce_urodzenia>
    <link>http://sylvesterstallone.com/</link>
    <filmy>
      <film kadr="img/rambo.jpg">
        <ID_filmu>RD-1982</ID_filmu>
        <tytul jezyk="polski">Rambo – Pierwsza krew</tytul>
        <tytul jezyk="angielski">Rambo - First Blood</tytul>
        <rok_premiery>1982-10-22</rok_premiery>
        <kraj>USA</kraj>
        <rezyser>
          <ID_osoby>TC-1931-T</ID_osoby>
          <imie>Ted</imie>
          <nazwisko>Kotcheff</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1931-04-07</data_urodzenia>
          <miejsce_urodzenia>Toronto</miejsce_urodzenia>
          <kolor_oczu>N/A</kolor_oczu>
        </rezyser>
        <gatunek>Dramat</gatunek>
        <gatunek>Wojenny</gatunek>
        <budzet>14000000</budzet>
      </film>
      <film kadr="img/rocky.jpg">
        <ID_filmu>RY-1978</ID_filmu>
        <tytul jezyk="polski">Rocky</tytul>
        <tytul jezyk="angielski">Rocky</tytul>
        <rok_premiery>1976-11-21</rok_premiery>
        <kraj>USA</kraj>
        <rezyser>
          <ID_osoby>JA-1935-O</ID_osoby>
          <imie>John</imie>
          <nazwisko>Avildsen</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1935-12-21</data_urodzenia>
          <miejsce_urodzenia>Oak Peak, Illinois</miejsce_urodzenia>
          <kolor_oczu>N/A</kolor_oczu>
        </rezyser>
        <gatunek>Dramat</gatunek>
        <gatunek>Sportowy</gatunek>
        <gatunek>Romans</gatunek>
        <budzet>225000000</budzet>
      </film>
    </filmy>
    <rodzina>
      <partner>
        Jennifer Flavin
      </partner>
      <dzieci>Sophie, Sistine Rose, Scarlet Rose</dzieci>
    </rodzina>
  </aktor>

  <aktor zdjecie="img/foster.jpg">
    <ID_osoby>JF-1962-L</ID_osoby>
    <imie>Jodie</imie>
    <nazwisko>Foster</nazwisko>
    <plec>kobieta</plec>
    <data_urodzenia>1962-11-19</data_urodzenia>
    <miejsce_urodzenia>Los Angeles, Kalifornia</miejsce_urodzenia>
    <link>https://en.wikipedia.org/wiki/Jodie_Foster</link>
    <filmy>
      <film kadr="img/lambs.jpg">
        <ID_filmu>TS-1991</ID_filmu>
        <tytul jezyk="polski">Milczenie owiec</tytul>
        <tytul jezyk="angielski">The Silence of the Lambs</tytul>
        <rok_premiery>1991-01-30</rok_premiery>
        <kraj>USA</kraj>
        <rezyser>
          <ID_osoby>TT-1952-W</ID_osoby>
          <imie>Ted</imie>
          <nazwisko>Tally</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1952-04-09</data_urodzenia>
          <miejsce_urodzenia>Winston-Salem, Karolina Północna</miejsce_urodzenia>
          <kolor_oczu>N/A</kolor_oczu>
        </rezyser>
        <gatunek>Thriller</gatunek>
        <budzet>272742922</budzet>
      </film>
      <film kadr="img/insideman.jpg">
        <ID_filmu>IN-2006</ID_filmu>
        <tytul jezyk="polski">Plan Doskonały</tytul>
        <tytul jezyk="angielski">Inside Man</tytul>
        <rok_premiery>2006-03-16</rok_premiery>
        <kraj>USA</kraj>
        <kraj>Wielka Brytania</kraj>
        <rezyser>
          <ID_osoby>SL-1957-A</ID_osoby>
          <imie>Spike</imie>
          <nazwisko>Lee</nazwisko>
          <plec>mezczyzna</plec>
          <data_urodzenia>1957-03-20</data_urodzenia>
          <miejsce_urodzenia>Atlanta, Georgia</miejsce_urodzenia>
          <kolor_oczu>N/A</kolor_oczu>
        </rezyser>
        <gatunek>Sensacyjny</gatunek>
        <gatunek>Thriller</gatunek>
        <budzet>184376254</budzet>
      </film>
    </filmy>
    <rodzina>
      <partner>
        Alexandra Hedison
      </partner>
      <dzieci>Charles Bernard Foster, Kit Bernard Foster</dzieci>
    </rodzina>
  </aktor>




</aktorzy>
